services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${WP_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WP_MYSQL_DATABASE}
      - MYSQL_USER=${WP_MYSQL_USER}
      - MYSQL_PASSWORD=${WP_MYSQL_PASSWORD}
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    volumes:
      - ./wp_data:/var/www/html
    ports:
      - ${WP_APP_IP}:${WP_APP_PORT}:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${WP_MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${WP_MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${WP_MYSQL_DATABASE}
  wpcli:
    image: wordpress:cli
    tty: true
    volumes:
      - ./wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${WP_MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "${WP_MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${WP_MYSQL_PASSWORD}"
    depends_on:
      - db
      - wordpress
    entrypoint: wp
    command: "--info"
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${WP_MYSQL_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 50M
    ports:
      - ${WP_APP_IP}:8080:80
    depends_on:
      - db
      - wordpress
volumes:
  db_data:
  wp_data: